language: node_js
node_js:
- 8.14.0
install:  yarn
script: gatsby build
deploy:
  provider: s3
  access_key_id:  $AWS_KEY
  secret_access_key:  $AWS_SECRET
  bucket: 'booch.io'
  skip_cleanup: true
  acl: public_read
  region: us-west-1
  local_dir: public