language: node_js
node_js:
- 8.14.0
cache:
  yarn: true
  directories:
    - node_modules
install:  yarn
script: yarn test
before_deploy:
  - yarn global add travis-ci-cloudfront-invalidation
  - yarn run build
deploy:
  provider: s3
  access_key_id:  $AWS_KEY
  secret_access_key:  $AWS_SECRET
  bucket: $S3_BUCKET
  skip_cleanup: true
  acl: public_read
  region: us-west-1
  local_dir: public
  on:
    branch: master
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_KEY -s $AWS_SECRET -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST